### ISSUE TITLE
[RFE] experiment yaml parser

### ISSUE THREAD

**Issue by grafuls** [grafuls/disruption-generator#4]
Issue to track development of yaml parser for experiments.

**Comment by grafuls** [comment]
We would like to have the ability to define disruptive actions via experiments in yaml format like this [example](https://github.com/grafuls/disruption-generator/blob/master/experiments/example.yaml)

**Comment by StLuke** [comment]
@ILpinto wanna take a look at this one?

**Comment by ILpinto** [comment]
Yes sure, will create parser for the yaml that will initialize dict with each disrupt action info

**Comment by grafuls** [comment]
#15
